version: 0.2
phases:
  install:
    commands:
        - npm install
  build:
    commands:
        - echo Build started on `date`
        - touch ./src/app/data/personal/confidential.ts
        - npm run build:web
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'